language: common-lisp

sudo: required

env:
  matrix:
    - LISP=sbcl COVERALLS=true
    - LISP=ccl
    # - LISP=clisp
    # - LISP=ecl
    # - LISP=abcl

install:
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^# cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
    fi
  # Coveralls support
  - git clone https://github.com/fukamachi/cl-coveralls ~/lisp/cl-coveralls

script:
  - cl -l prove -l cl-coveralls
       -e '(in-package :cl-user)'
       -e '(setf prove:*debug-on-error* t)'
       -e '(setf *debugger-hook*
                 (lambda (c h)
                   (declare (ignore c h))
                   (uiop:quit -1)))'
       -e '(coveralls:with-coveralls (:exclude (list "t"))
             (ql:quickload :cl-isaac))'
       -e '(or (prove:run :cl-isaac-test)
                 (uiop:quit -1))'

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/af170795664a18762462
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
